### ISSUE TITLE
Could this library be used to compute permutations of a tree based on node values?

### ISSUE THREAD

**Issue by DaveSlinn** [eoincampbell/combinatorics#12]
Suppose I have a tree with a single root node A.  A has 3 child nodes, B, C and D.  B as 2 child nodes, E and F.  So:

```
      A
    / | \
   B  C  D
  / \
 E   F
```
Now let's say every node could have a value of 0 or 1.  If the node value is 0, child nodes should be ignored and not included in the permutation.  

I want to compute every possible permutation of this tree, so it would go something like this:

Permutation 1: Value of node A = 0.  Therefore, the complete tree of P1 is node A only, since we ignore it's child nodes.
```
      A(0)
```

Permutation 2: Node values are A = 1, B=0, C=0 and D=0.  We ignore B's children since B=0, giving us a tree of A, B, C and D only.
```
        A(1)
      /  |  \
   B(0) C(0) D(0)
```

Permutation 3: Values are A=1, B=0, C=0 and D=1.
```
        A(1)
      /  |  \
   B(0) C(0) D(1)
```

Permutation 4: Values are A=1, B=0, C=1 and D=0.
```
        A(1)
      /  |  \
   B(0) C(1) D(0)
```

Permutation 5: 
```
        A(1)
      /  |  \
   B(0) C(1) D(1)
```

Permutation 6:
```
        A(1)
      /  |  \
   B(1) C(0) D(0)
  /    \
E(0)   F(0)
```

and so on until the final permutation would be:
```
        A(1)
      /  |  \
   B(1) C(1) D(1)
  /    \
E(1)   F(1)
```

Which would be the 11th permutation.  Can I use the Permutations class in this library against a tree data structure, and have it handle conditional logic during it's computation?

**Comment by eoincampbell** [comment]
Hi Dave, the combinations library can't be made "tree-aware". so I think you'd have to do this in a couple of parts.

First, you'd create your full tree structure as you describe. Each node would have an `T Id` and `bool displayChildren` value.

Second, you could use the Variations data structure to generate all possible variation of true/false for the number of nodes you have. 

    Variations<bool> allVariations = new Variations<bool>(new List<bool> { true, false }, 6, GenerateOption.WithRepetition);

Next, you could recursively iterate through your tree and set each nodes, `displayChildren` property to the appropriate true/false value from each variation.

I threw a very rough example up here: https://dotnetfiddle.net/I1Jj6R

Just be aware that this might create a lot of duplicate tree structures... so you might have to iterate over the resultant trees one last time to remove dupes. e.g. the following 2 examples on the left are technically different variations due to the `E` & `F` values,  but since `B` is set to `false`, they'll both render the same.

            A(1)              A(1)                   A
          /  |  \           /  |  \                / | \
       B(0) C(0) D(0)    B(0) C(0) D(0)           B  C  D
      /    \            /    \                   
     E(1)   F(0)       E(0)   F(1)

**Comment by DaveSlinn** [comment]
Apologies for not responding sooner - thank you so much for your response, including code sample demonstrating it.  I did manage to create a routine that would compute every permutation a couple days after I had logged this issue, albeit not using your library.  That code is here: https://github.com/DaveSlinn/TraverseTree 

My issue then became a problem with the number of permutations and the efficiency (or should I say inefficiency) of my routine.  The tree in question for our project had 51 nodes, with a max depth of 5 on some branches.  We computed the number of permutations of this tree to be something like 7.1 trillion - far too many to do anything with realistically.  We have since strayed away from even attempting to evaluate and test each permutation and are instead, performing a more explicit test by using predefined scenarios.
