### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by StephenCleary** [eoincampbell/combinatorics#14]
Could use some updates: `IReadOnlyList`, netstandard 2, source linking, etc.

Is this library still maintained? If not, I could fork and update it.

**Comment by eoincampbell** [comment]
Hey Stephen

At this stage, I'm barely still maintained :-)

But yes, I'd be happy to make some suggested changes, or accept PRs. I picked it up out of necessity years ago from the original author so that I could package it up and put the package up on nuget but you're right, it's probably in need of some TLC. If you have a wish list, I'd be happy to divvy up the tasks between us ?

**Comment by StephenCleary** [comment]
I started looking at the changes I'd like to make, and it's pretty extensive. I could open multiple PRs or a massive PR, or if you don't want to mess with it, I could just work off [my own fork](https://github.com/StephenCleary/Combinatorics). Just let me know what you prefer.

**Comment by eoincampbell** [comment]
yeah if you're happy to do that Stephen and push back one big PR that'd be great & much appreciated. Happy as well to take a WIP PR and tidy it up if you're just trying to get something up and working. 

I know there are people still using/downloading the current version from nuget.org so I can leave the legacy version there and then bump the version number on it when you push it back. 👍

**Comment by jzabroski** [comment]
I'd be willing to take over maintenance of this if you don't have time, @eoincampbell .  Not trying to be presumptuous, just reading into the comment that "At this stage, _I'm_ barely still maintained :-)" as a potential ask for help.  It's a really useful library for brute force testing some assumptions.

For example, right now, I want to verify that a port of some T-SQL function `dbo.tvf_GetMinimumPositiveDecimal` is equivalent to some C# logic. What I usually do is auto-generate the InlineData for xunit, rather than statically link to your library. (So, your library is probably used more than you think).

e.g.,

```c#
var variation = new Variations<int?>(new[] { 1, (int?)null, 0, -1, int.MaxValue }, 4, GenerateOption.WithRepetition);

foreach (var v in variation)
{
	var v0 = v[0] == null ? "null" : v[0] == int.MaxValue ? "int.MaxValue" : v[0].ToString();
	var v1 = v[1] == null ? "null" : v[1] == int.MaxValue ? "int.MaxValue" : v[1].ToString();
	var v2 = v[2] == null ? "null" : v[2] == int.MaxValue ? "int.MaxValue" : v[2].ToString();
	var v3 = v[3] == null ? "null" : v[3] == int.MaxValue ? "int.MaxValue" : v[3].ToString();
	var minV = v.Select(n => n ?? 0).Where(n => n > 0).DefaultIfEmpty().Min();
	var minVstring = minV == int.MaxValue ? "int.MaxValue" : minV.ToString();
	Console.WriteLine($"[InlineData({minVstring}, {v0}, {v1}, {v2}, {v3})]");
}
```

I then just call my SQL Table Valued Function using my DAL, and compare actual to expected.

**Comment by eoincampbell** [comment]
@StephenCleary @jzabroski 

Guys, very sorry it took so long to get back to this. Picking it up right now and will get house cleaned. @jzabroski may take you up on that. My role has somewhat changed and not doing much day-to-day coding anymore so it's a while since I've even logged into github/opened an IDE.

**Comment by eoincampbell** [comment]
Just as a quick follow up, there are a few issues blocking me from publishing this package. Mainly the fact that it was originally created using the CPOL from Code Project which is not considered acceptably open by FSF/OSI/Nuget. I'll update this to Apache2 but just wanted to make you both aware.

**Comment by StephenCleary** [comment]
I'm good with that. Feel free to relicense my contribution however you want.

**Comment by eoincampbell** [comment]
@StephenCleary thanks stephen, appreciate the quick response.

**Comment by jzabroski** [comment]
Thanks @stephencleary

**Comment by eoincampbell** [comment]
There's a [2.0.0 package available on nuget.org ](https://www.nuget.org/packages/Combinatorics/) now and the GithubActions CI pipeline is doing an autodeploy on push and version bump . there's a small issue with the BenchMark project but I'll try sort that over the weekend -  I think the BenchMark runner is targetting netfw which is causing issues on the ubuntu server that's doing the building. going to close this issue for now. Thanks both.

**Comment by bryanrideshark** [comment]
Thank you @StephenCleary for your work on this.
